### ISSUE TITLE
Your site is broken

### ISSUE THREAD

**Issue by 4lejandrito** [nikitkrsk/portfolio#6]
Hi @nikitkrsk!

I am linking to your site from https://github.com/4lejandrito/creepyface. I noticed it is no longer working. 

I will remove it for now. If you ever fix it I'll add it back 😊.

**Comment by nikitkrsk** [comment]
> Hi @nikitkrsk!
> 
> I am linking to your site from https://github.com/4lejandrito/creepyface. I noticed it is no longer working.
> 
> I will remove it for now. If you ever fix it I'll add it back .

Hello, 

Tahnk you for mention it. I forgot to pay for my domain name. Will wait till it got released from fees and will let you know.
